<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_schedule</name>
   <tag></tag>
   <elementGuidId>d4463b84-79e6-4c08-8c53-c4c5aa6921f6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#bookApptButton</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='bookApptButton']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>811247f8-6fa6-4b62-9371-b3173c120d00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiButtonBase-root MuiButton-root MuiButton-text MuiButton-textPrimary MuiButton-sizeMedium MuiButton-textSizeMedium MuiButton-colorPrimary MuiButton-root MuiButton-text MuiButton-textPrimary MuiButton-sizeMedium MuiButton-textSizeMedium MuiButton-colorPrimary cooler-reder-button css-1e6y48t-MuiButtonBase-root-MuiButton-root</value>
      <webElementGuid>7818e6ed-9713-46be-8ffe-90ee368e1b3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>3385829d-88a6-45dc-9bf9-6081d6517216</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>bookApptButton</value>
      <webElementGuid>b941f59d-6da9-45b7-bceb-d7fa00eb8c7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/bookAppt</value>
      <webElementGuid>d7e8cbe4-fa36-4d17-ae75-9c968e6dbb87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>schedule </value>
      <webElementGuid>2ad5f3af-4a0e-4c07-9cb5-0d3048b923b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/main[1]/div[1]/div[@class=&quot;homepage p-3&quot;]/div[@class=&quot;px-5 mx-5&quot;]/div[@class=&quot;d-flex justify-evenly mt-5&quot;]/div[1]/a[@id=&quot;bookApptButton&quot;]</value>
      <webElementGuid>e0b349be-8896-4183-9b33-616b8b089a16</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='bookApptButton']</value>
      <webElementGuid>aa5f46d7-47d0-4909-a4ca-5746530d4a56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/main/div/div/div/div[5]/div/a</value>
      <webElementGuid>cc38e530-e7e7-4783-bbbb-7bc05b0faae1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'schedule')]</value>
      <webElementGuid>0be9cff8-a49d-477e-896f-a552a514c4ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Book Appointment'])[1]/following::a[1]</value>
      <webElementGuid>508c078f-4084-4653-afc0-a4cad84ee883</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View Car Status'])[1]/preceding::a[1]</value>
      <webElementGuid>07653df2-fb93-4748-a827-d656f3be6121</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View'])[1]/preceding::a[1]</value>
      <webElementGuid>2eb5d949-08c0-418c-babc-2f821720a545</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='schedule']/parent::*</value>
      <webElementGuid>43818f80-8808-47f9-929f-9576a83854cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/bookAppt')]</value>
      <webElementGuid>94ac2a1e-def5-4e3c-94c4-02b7c0a4f2ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/a</value>
      <webElementGuid>3ce967b8-ff37-462f-bf6e-ebcc9181dee0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'bookApptButton' and @href = '/bookAppt' and (text() = 'schedule ' or . = 'schedule ')]</value>
      <webElementGuid>4ed0d719-0f23-4370-b88a-1d1a97aea814</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
