<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Edit Appointment</name>
   <tag></tag>
   <elementGuidId>e7009d2b-07d6-45c9-9860-d470345c61d5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button[value=&quot;16&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@value='16']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>503dca8f-5b5f-471d-b771-38f212bc26d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>16</value>
      <webElementGuid>43a53052-0058-4a85-b11a-c619c12ec1bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Edit Appointment</value>
      <webElementGuid>e24c78b5-165c-4e50-8356-99b1f65081c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/main[1]/div[1]/div[1]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;row justify-content-center&quot;]/div[@class=&quot;col-lg-10 col-md-12&quot;]/div[1]/div[@class=&quot;table-responsive&quot;]/table[@class=&quot;table table-bordered table-striped&quot;]/tbody[1]/tr[2]/td[6]/button[1]</value>
      <webElementGuid>bea07f83-07cc-460f-a93c-983619f7c70d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@value='16']</value>
      <webElementGuid>8ed9c62c-7236-4305-ac87-a2f3b5771188</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/main/div/div/div/div/div/div/div/table/tbody/tr[2]/td[6]/button</value>
      <webElementGuid>59909224-6704-4a3b-904d-185e028a4a99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Scheduled'])[1]/following::button[1]</value>
      <webElementGuid>4e46bbf1-bdb7-426a-98a5-e978b5caa71e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Air Conditioner Recharge'])[1]/following::button[1]</value>
      <webElementGuid>3a81e013-cbf1-4daa-9334-1f9da34caaa3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Oil Change'])[2]/preceding::button[1]</value>
      <webElementGuid>e92139ec-b0d8-47f1-a7df-dfeb450e5f2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Scheduled'])[2]/preceding::button[1]</value>
      <webElementGuid>f441991d-37b2-4699-994c-926bcfedaf47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[6]/button</value>
      <webElementGuid>0a9689b9-6351-4711-9e35-aba3d751908f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Edit Appointment' or . = 'Edit Appointment')]</value>
      <webElementGuid>bc100af4-c29b-4794-9b16-9888d4ed3ddb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@value='9']</value>
      <webElementGuid>09e388b3-6ced-4d3b-8e35-7fade162e7e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/main/div/div/div/div/div/div/div/table/tbody/tr/td[6]/button</value>
      <webElementGuid>b05b65c0-63b9-4c77-bb77-e2b8bad7bac4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Oil Change'])[1]/following::button[1]</value>
      <webElementGuid>2cfef1b6-b587-42a5-94a0-1e603f7583d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='JN8AZ2KRXET870589'])[1]/preceding::button[1]</value>
      <webElementGuid>cf7a3fcc-79ed-48dc-803a-be82a9070ab5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Air Conditioner Recharge'])[1]/preceding::button[1]</value>
      <webElementGuid>5e60b389-abda-40fa-888e-9dbb3314f6ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Edit Appointment']/parent::*</value>
      <webElementGuid>258d2ef9-3b3c-4c59-aa54-c3830bd96eab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[6]/button</value>
      <webElementGuid>a7d659b6-7ddc-4cea-a3f7-1ee3498ce98a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
