<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Close (3)</name>
   <tag></tag>
   <elementGuidId>ece52e3a-2fd5-449c-9477-1593209c9ccd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.rounded.bg-gray-50.px-4.py-2.text-sm.font-medium.text-gray-600</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit Appointment'])[3]/following::button[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ce4b0aae-6eec-40dc-9b2c-0222b1fa947e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rounded bg-gray-50 px-4 py-2 text-sm font-medium text-gray-600</value>
      <webElementGuid>9b26db4e-a6f2-44f2-8cf2-2299e2f1b56c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Close</value>
      <webElementGuid>a9ac9aab-4d86-4447-8a7d-8fb3df2fbceb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;MuiModal-root css-79ws1d-MuiModal-root&quot;]/div[@class=&quot;MuiBox-root css-3hcm5q&quot;]/div[@class=&quot;rounded-lg bg-white p-8 shadow-2xl&quot;]/button[@class=&quot;rounded bg-gray-50 px-4 py-2 text-sm font-medium text-gray-600&quot;]</value>
      <webElementGuid>50973d4f-efc4-4c95-9e97-2215b656be47</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit Appointment'])[3]/following::button[1]</value>
      <webElementGuid>6622cf7a-3ad9-435d-be6b-d9fed2cbca28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Close']/parent::*</value>
      <webElementGuid>ce380f78-ccfe-4f02-9d93-5ad9ba6f1685</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/button</value>
      <webElementGuid>3edb95a1-f03f-46c9-8fea-f1676ba1bc5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Close' or . = 'Close')]</value>
      <webElementGuid>e6d6f88e-15c9-4575-94e8-379f63abc92d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
