<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_SSN_SSN</name>
   <tag></tag>
   <elementGuidId>80567aea-333a-42c2-8324-6fe5ecefbc42</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#SSN</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='SSN']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>db330738-a1d5-49d0-9a17-b97f35d61f25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ee4b56ac-a4bd-4fff-9e02-e82993117e8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>SSN</value>
      <webElementGuid>41d806be-2d47-4b28-8dfa-6327816b8578</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>SSN</value>
      <webElementGuid>f8eaedb4-fe06-46d7-9ec1-41026edf5896</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>45b31d78-38f7-4f90-8810-bd07bde24d55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SSN&quot;)</value>
      <webElementGuid>aa78e83d-44a9-4ca7-b9f7-b1f1c0db0ccf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='SSN']</value>
      <webElementGuid>2ab8fc45-e7d0-41ab-befc-e42432ed4a4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/main/div/div[2]/form/div[12]/input</value>
      <webElementGuid>8ddde5ec-91e6-4849-a784-f758952595d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/input</value>
      <webElementGuid>e081cc1d-2c18-40dd-87bd-1dc08eb01ace</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'SSN' and @name = 'SSN']</value>
      <webElementGuid>4cd7d076-1ab7-414f-bdd5-11a8f84eacb3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
