<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Routing number_routing-number</name>
   <tag></tag>
   <elementGuidId>a8a03858-428c-4a1d-b956-f60940c7d4ae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#routing-number</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='routing-number']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>aa2cea61-5d92-4220-8707-fa85139f5ddf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>4ddb1d59-5607-4c43-826c-674cebddd438</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>routing-number</value>
      <webElementGuid>2553c26c-27dc-4410-84a6-dac9a7aed708</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>routing-number</value>
      <webElementGuid>bb9e6401-1797-408a-8993-390c4ad2b61a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>123456789</value>
      <webElementGuid>15a6988d-d059-49d7-bc5b-c49d00fe4bd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8ca7dd70-be23-470c-8483-eb7ded03cb6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>9</value>
      <webElementGuid>c3e896a0-e614-4c20-ac98-5c6b5935c083</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input MuiOutlinedInput-input css-1t8l2tu-MuiInputBase-input-MuiOutlinedInput-input</value>
      <webElementGuid>3c0ef5d4-ddfe-494b-95e8-08e20d54eebf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;routing-number&quot;)</value>
      <webElementGuid>f4938f3b-13c1-4e7e-b022-c19e115a4a82</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='routing-number']</value>
      <webElementGuid>e2d65d55-a410-47cb-95d1-067b04f68ec1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/main/div/div[2]/div[3]/div[2]/div/div/div[2]/div/div/input</value>
      <webElementGuid>095a2f57-1ee0-496f-ab62-d0c8134484ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>7d9d1fb9-8c0f-4fae-918b-afa138a726e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'routing-number' and @placeholder = '123456789' and @type = 'text']</value>
      <webElementGuid>46f381f5-7a79-471e-ae12-8abbb923b0c0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
