<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Vin_VIN_carID</name>
   <tag></tag>
   <elementGuidId>ae3a757a-0438-47d3-9836-e7a6214ac842</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#VIN_carID</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='VIN_carID']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b0796590-b8d2-4cba-b55e-a3e50e917631</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f69767e4-5c36-43a2-86e3-fc8e2ca9b581</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>VIN_carID</value>
      <webElementGuid>e965946c-1a4f-4c58-8074-37bddfb0f1a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>VIN_carID</value>
      <webElementGuid>e7008705-ac22-4542-a122-a635364d1b40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d72bf02a-ebc8-4ac4-9709-2cd0b2550baa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;VIN_carID&quot;)</value>
      <webElementGuid>aa84b64e-653e-4516-b2a5-34d1cb3ca75d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='VIN_carID']</value>
      <webElementGuid>273a380b-0fdb-489f-b440-29608664d3c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/main/div/div[2]/form/div/input</value>
      <webElementGuid>e3c45c8a-e804-429c-b3d1-cced7d7d3a40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>5fa8ce09-ffd1-4ccd-8572-8afd438af079</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'VIN_carID' and @name = 'VIN_carID']</value>
      <webElementGuid>b337594c-348d-4808-9fd0-2b3395980943</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
