<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Service Price_editedPrice</name>
   <tag></tag>
   <elementGuidId>ef5144b7-e217-4f9c-a2fc-299ae4fb094e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#editedPrice</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='editedPrice']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>66040520-79f7-4139-8df5-a200eddab5c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>editedPrice</value>
      <webElementGuid>132b1347-ec5f-40da-90ec-836b19a94faa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>167c94bc-064a-41ab-8e03-1c1ad3611dfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>99.99</value>
      <webElementGuid>f3dffa51-b65c-4ab2-9ca7-f5a4ba1ef9fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;editedPrice&quot;)</value>
      <webElementGuid>f9540654-56d8-4890-8dec-60d99c2d1f27</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='editedPrice']</value>
      <webElementGuid>1ba0b67e-69fe-4857-9fd7-82d9c5ef36f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/main/div/div[2]/div/div/div[3]/div/div/div[2]/div[2]/input</value>
      <webElementGuid>10a4d6d0-045c-4dc1-966e-b2bc15872711</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/input</value>
      <webElementGuid>1d981d14-8b68-4f3a-9984-9e4b50c6ce66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'editedPrice' and @type = 'text']</value>
      <webElementGuid>82c1ebc8-0e72-4cad-832c-18d0ddf79f3f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
