<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Max_maxYear-number</name>
   <tag></tag>
   <elementGuidId>851eeda1-4acb-4b76-aa41-91b4ddd1d83b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#maxYear-number</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='maxYear-number']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fbb631cb-16b8-4374-bbbe-150973f9228d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>f62e9a1a-ff41-4e11-9c53-f5d22fed222e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>maxYear-number</value>
      <webElementGuid>ab0f7b9a-0055-4a34-84e3-ae9d102d08dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>acd12172-9b15-41ba-8eb7-d0b0622623ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input MuiOutlinedInput-input MuiInputBase-inputSizeSmall css-1n4twyu-MuiInputBase-input-MuiOutlinedInput-input</value>
      <webElementGuid>db3b3bf6-7339-4359-abdc-982cdc093f47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;maxYear-number&quot;)</value>
      <webElementGuid>c9134295-ee77-4635-9de0-f144447651a7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='maxYear-number']</value>
      <webElementGuid>c891d5eb-9a3f-4e7a-81cb-e90873231889</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/main/div/div[2]/div/div/div[2]/ul/li/ul/li[2]/div[2]/div/input</value>
      <webElementGuid>6c099445-6408-45d8-84c2-cf5b45042c80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>ca8d6a2c-5bbb-4bd8-aed5-6fd006002150</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'maxYear-number' and @type = 'number']</value>
      <webElementGuid>e794a434-7f45-437d-811c-d0bbc0f3d30b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
