<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Customer Signature_customer-signature</name>
   <tag></tag>
   <elementGuidId>06630ad0-0be4-4196-8756-88839a58d151</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#customer-signature</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='customer-signature']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1b8f1acc-e7b2-4690-bf18-a42db3a24100</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>68b8fb65-8748-4280-8787-2139cb623579</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>customer-signature</value>
      <webElementGuid>fc9e2608-e18e-4fd2-9cf1-d3d00214a1e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>customer-signature</value>
      <webElementGuid>64e021e7-7510-411f-8373-1c5679938621</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Sign Here: Alice Smith</value>
      <webElementGuid>1bfd0ff4-2be8-455f-8f18-4bdfe6a28909</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>13e73235-1034-4c48-b205-4e887b0b3f67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input MuiOutlinedInput-input css-1t8l2tu-MuiInputBase-input-MuiOutlinedInput-input</value>
      <webElementGuid>0607c9e9-3eb8-4b31-9606-52a68a2ee6f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;customer-signature&quot;)</value>
      <webElementGuid>f94ad508-f8e1-47af-9493-cff4c6bc68c2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='customer-signature']</value>
      <webElementGuid>2add2190-37df-4849-9bbc-a2d06ffd6c2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/main/div/div[2]/div[3]/div[2]/div/div/div/input</value>
      <webElementGuid>8c3a3eb9-94e2-4995-b2e0-4907ad23c44e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>13e7f381-dfd5-4752-8e2b-9cab81082c4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'customer-signature' and @placeholder = 'Sign Here: Alice Smith' and @type = 'text']</value>
      <webElementGuid>2dff5a37-4e78-4174-94c4-a270ded1933e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
