<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Mileage_mileage</name>
   <tag></tag>
   <elementGuidId>b190ba6b-1eda-4c28-af8f-19e50b07187c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mileage</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mileage']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a3ef9280-5fcc-491d-a83d-217b9cce429d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>346be0ed-4d1a-4b8a-8016-886add01c3ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mileage</value>
      <webElementGuid>b99bf64b-6189-40a0-bafa-0016d2251665</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>mileage</value>
      <webElementGuid>0a997383-8f13-4cf2-9a54-389e4f6c27f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3f017a12-10af-4578-99ab-3b519d97423c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mileage&quot;)</value>
      <webElementGuid>6b64eac4-c320-401e-8df3-41e512b453f3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mileage']</value>
      <webElementGuid>f09702d6-e274-47a4-b688-9d9a85a1c21e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/main/div/div[2]/form/div[7]/input</value>
      <webElementGuid>65c54afe-a68b-484b-853d-9b040270efa5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/input</value>
      <webElementGuid>12aa36d2-2500-46cb-8f93-b96c2a4cdda1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'mileage' and @name = 'mileage']</value>
      <webElementGuid>cad3e1a5-4318-49fe-a27b-9e89354904c1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
