<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Service Price_editedPrice (1)</name>
   <tag></tag>
   <elementGuidId>73821fdc-d9e5-4549-a14c-67ae288c18a6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#editedPrice</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='editedPrice']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>05d50e9a-c8d2-4775-b4df-d67fb1b1ccff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>editedPrice</value>
      <webElementGuid>31b9e216-901d-480f-ac64-ef221e3498c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6178dad6-497b-411a-8b18-23ba91360419</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>99.99</value>
      <webElementGuid>c1d534c4-dbe3-4100-98f4-e68d4eaf3df7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;editedPrice&quot;)</value>
      <webElementGuid>048d36ca-a26c-417f-a618-f6cd7a004b4b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='editedPrice']</value>
      <webElementGuid>21959030-5f57-40c8-b6a9-26426d2008e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/main/div/div[2]/div/div/div[3]/div/div/div[2]/div[2]/input</value>
      <webElementGuid>4e36471f-ce73-476d-86fc-b8784d9380ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/input</value>
      <webElementGuid>b364abdf-f033-425e-ac94-646b8944bf25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'editedPrice' and @type = 'text']</value>
      <webElementGuid>557871d1-7354-4b3f-a2b9-5a8a5d1f0706</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
