<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Min_minYear-number</name>
   <tag></tag>
   <elementGuidId>04335e9b-773e-49af-95da-a287a8e38465</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#minYear-number</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='minYear-number']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ad7d5c60-4b92-432d-967a-cba6959b64b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>039dbef0-4c2d-4abb-937b-5107544e8015</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>minYear-number</value>
      <webElementGuid>66af9be7-458f-449b-b84e-04d30c2e25bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>5a262ba2-4e1a-4fcb-b572-27df8022cd5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input MuiOutlinedInput-input MuiInputBase-inputSizeSmall css-1n4twyu-MuiInputBase-input-MuiOutlinedInput-input</value>
      <webElementGuid>363f246c-5198-4bd5-86c6-0ecf6326dd6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;minYear-number&quot;)</value>
      <webElementGuid>d1a6f6cb-d4c3-4baa-81ed-d7046db605cd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='minYear-number']</value>
      <webElementGuid>525bc127-0974-469d-b6f0-9b7c5e96cbd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/main/div/div[2]/div/div/div[2]/ul/li/ul/li[2]/div/div/input</value>
      <webElementGuid>c8381875-41cd-49e9-92e3-bd8fd741691b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div/div/input</value>
      <webElementGuid>feb83e76-4c14-4009-943f-fcdd843cfc67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'minYear-number' and @type = 'number']</value>
      <webElementGuid>e7a69c55-fa9f-410d-a79d-dce61af90fff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
