<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Drivers License ID</name>
   <tag></tag>
   <elementGuidId>e954f3ba-735a-407d-975e-f297038db322</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#driverID-label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='driverID-label']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>268763c6-fc60-46ed-871d-9de4418d165e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiFormLabel-root MuiInputLabel-root MuiInputLabel-formControl MuiInputLabel-animated MuiInputLabel-shrink MuiInputLabel-sizeMedium MuiInputLabel-outlined MuiFormLabel-colorPrimary Mui-focused Mui-required MuiInputLabel-root MuiInputLabel-formControl MuiInputLabel-animated MuiInputLabel-shrink MuiInputLabel-sizeMedium MuiInputLabel-outlined css-1jy569b-MuiFormLabel-root-MuiInputLabel-root</value>
      <webElementGuid>f5516d07-4912-4a0d-84d7-812706e8b54f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-shrink</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>13d4cbd0-5d97-4f0e-9ae0-d9f171cfa5b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>driverID</value>
      <webElementGuid>00bbac73-5ba7-4868-b022-f60b20693eff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>driverID-label</value>
      <webElementGuid>e7c6d0bb-2dbd-4d1a-b07b-b1a92022bef1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Driver's License ID *</value>
      <webElementGuid>6c9988e2-d882-4d48-a86f-810df0dbf5d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;driverID-label&quot;)</value>
      <webElementGuid>7d223cf2-786c-4954-9d47-941077378318</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='driverID-label']</value>
      <webElementGuid>7418038e-446c-4d78-99e8-869db49f7c74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/main/main/div/form/div/div[5]/div/label</value>
      <webElementGuid>680d5c03-208f-4000-8b80-21bbb18aded8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/label</value>
      <webElementGuid>5a8abace-725e-4b4a-9868-bb36abd4228b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'driverID-label' and (text() = concat(&quot;Driver&quot; , &quot;'&quot; , &quot;s License ID *&quot;) or . = concat(&quot;Driver&quot; , &quot;'&quot; , &quot;s License ID *&quot;))]</value>
      <webElementGuid>d4f2fe8f-3bda-4907-b730-9c93e8c4b72b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
