<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_AnySilverBlackWhiteGreenGrayBlueRedOrange</name>
   <tag></tag>
   <elementGuidId>46828b75-ecd8-4400-a34c-81162336a726</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#color-select</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='color-select']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>288abfc3-8085-4904-8228-c8a0b7149b72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiNativeSelect-select MuiNativeSelect-outlined MuiInputBase-input MuiOutlinedInput-input MuiInputBase-inputSizeSmall css-12ogz78-MuiNativeSelect-select-MuiInputBase-input-MuiOutlinedInput-input</value>
      <webElementGuid>f26c5edc-ce07-4457-b81c-63e295d8aacb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>2ba979d7-3da7-43a8-825f-02a30dd712bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>color-select</value>
      <webElementGuid>c1e3bc7e-a7f0-4d9b-8a74-3c41f4e949bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AnySilverBlackWhiteGreenGrayBlueRedOrange</value>
      <webElementGuid>042d10c1-3a10-48e6-a0b9-af692fe88c47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;color-select&quot;)</value>
      <webElementGuid>fffa76ed-46d9-438e-9afd-1e697a66b983</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='color-select']</value>
      <webElementGuid>71755811-2f6f-4ffc-8e22-42333bcc7e55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/main/div/div[2]/div/div/div[2]/ul/li[4]/ul/li[2]/div/div/select</value>
      <webElementGuid>aa226e06-ac78-44f0-aec9-507a60bbc8dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Color'])[1]/following::select[1]</value>
      <webElementGuid>ecc5bd06-f718-4c9e-a5ac-91f7012c8573</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Max'])[6]/following::select[1]</value>
      <webElementGuid>25cb0f8f-8a63-41e0-ad17-b94bdbe1a9c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='​'])[1]/preceding::select[1]</value>
      <webElementGuid>c4d41a92-b121-4940-b142-0834220bf8e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Make'])[1]/preceding::select[1]</value>
      <webElementGuid>800cee79-681f-45e0-823c-3fb941528fd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>0050b1bd-a446-4825-b7cd-5d6ffe08f2a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'color-select' and (text() = 'AnySilverBlackWhiteGreenGrayBlueRedOrange' or . = 'AnySilverBlackWhiteGreenGrayBlueRedOrange')]</value>
      <webElementGuid>07c99989-3f46-4bab-afc5-908cca72d225</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
