<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select modelILXIntegraRLRSXTLTLXTSX</name>
   <tag></tag>
   <elementGuidId>3f5facdc-d731-475c-b35b-2271d219ec5c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#model</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='model']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>90659f3e-5e1d-4c05-a292-3588a5139428</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>model</value>
      <webElementGuid>829e400b-5b4d-4e94-997f-7d05cc862caa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>model</value>
      <webElementGuid>73824b10-7334-4adb-83f3-d483a574e70b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5acaa503-23a0-4fd8-a106-31d98d8b993c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select modelILXIntegraRLRSXTLTLXTSX</value>
      <webElementGuid>d35d5ab9-3350-46ba-9a34-d97d5b7496a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;model&quot;)</value>
      <webElementGuid>ff105ebc-d474-40ea-b2c9-7534a08eba5f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='model']</value>
      <webElementGuid>9e0ed190-fba5-4893-aa1f-8b14840ba19e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/main/div/div[2]/form/div[3]/select</value>
      <webElementGuid>f3df6928-a687-4337-8b2c-2140a148c9d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Model:'])[1]/following::select[1]</value>
      <webElementGuid>e6bfd83d-8d9d-4c80-86dc-a057c8f7b775</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Make:'])[1]/following::select[2]</value>
      <webElementGuid>da7900c3-70ed-4a58-b344-186a72e0cf6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Body:'])[1]/preceding::select[1]</value>
      <webElementGuid>791ecf04-3148-477c-bb72-44e6ecd1be41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Year:'])[1]/preceding::select[2]</value>
      <webElementGuid>828d09fd-6939-4d61-baac-8f2d74ca42d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/select</value>
      <webElementGuid>e90dabf3-d9a1-4500-808b-70f9357e2c10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'model' and @name = 'model' and (text() = 'Select modelILXIntegraRLRSXTLTLXTSX' or . = 'Select modelILXIntegraRLRSXTLTLXTSX')]</value>
      <webElementGuid>e0e40347-d586-4a0a-bfd2-55ff1eef2d40</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
