<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_ScheduledDoneCancelled</name>
   <tag></tag>
   <elementGuidId>4d2d1f30-15c1-4d30-8cd2-f2edfdfe8262</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#newStatus</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='newStatus']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>aa0ea42a-de4a-4ea1-96a8-e9d4ff44e9e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500</value>
      <webElementGuid>503bc04a-8ef0-4d05-bc13-c7ff20231843</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>newStatus</value>
      <webElementGuid>7d970759-49b3-48a3-ac24-ce2242ea40f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ScheduledDoneCancelled</value>
      <webElementGuid>481d75c1-4713-4de6-994b-b431f3138911</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;newStatus&quot;)</value>
      <webElementGuid>3cd86903-65e4-4cff-9f2d-8c9e7bdcf4f6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='newStatus']</value>
      <webElementGuid>26199af6-1979-4de3-9bb1-f362d0860bfc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//p[@id='modal-modal-description']/select</value>
      <webElementGuid>316aa6b6-95b8-4aaf-a708-24cfe97d4172</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Update Appointment'])[1]/preceding::select[1]</value>
      <webElementGuid>c61ac85d-ace7-4590-ba57-e0ad4e0ae89a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close'])[1]/preceding::select[1]</value>
      <webElementGuid>13ca839a-a55d-47e0-80b7-33e7b005ea82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>b4d9476d-3640-4a92-9934-0af7dc3da25d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'newStatus' and (text() = 'ScheduledDoneCancelled' or . = 'ScheduledDoneCancelled')]</value>
      <webElementGuid>18712779-ea98-42c6-8dae-827adfec0f5a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
