<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select makeAcuraAudiBMWBuickCadillac_aa9f37</name>
   <tag></tag>
   <elementGuidId>57714f6b-d5fe-4274-a55d-9e9b9a63ac8c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#make</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='make']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>ac262536-22ca-4ab5-9d7e-e6ee34156967</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>make</value>
      <webElementGuid>3131beb3-11a0-47ce-bf2c-51a2bab2a876</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>make</value>
      <webElementGuid>65cc787e-0f5f-4802-a8f0-215f4c1fdd45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>827a2f8b-bba3-454a-9d3d-ea19314600c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select makeAcuraAudiBMWBuickCadillacChevroletChryslerDodgeFiatFordGMCHondaHummerHyundaiInfinitiJaguarJeepKiaLand RoverLexusLincolnMazdaMercedesMercuryMitsubishiNissan</value>
      <webElementGuid>1eeab5ac-3db9-469f-b5e0-636efdccf0bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;make&quot;)</value>
      <webElementGuid>889653fc-1422-4427-8d40-1c4eae7d7da3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='make']</value>
      <webElementGuid>c76dd43d-f536-4e64-a972-24a8922b87a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/main/div/div[2]/form/div[2]/select</value>
      <webElementGuid>bb474be9-ebcd-4c8c-ad08-fbc7f31a0032</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Make:'])[1]/following::select[1]</value>
      <webElementGuid>a8bb2ab2-4bcb-4181-a2c9-82fd70194e8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vin:'])[1]/following::select[1]</value>
      <webElementGuid>bf8bb84d-725d-44e0-a524-3360ff612564</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Model:'])[1]/preceding::select[1]</value>
      <webElementGuid>2aee2265-3d7c-46a1-adbb-c438fd022c5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Body:'])[1]/preceding::select[2]</value>
      <webElementGuid>5bf265f4-4463-49de-a384-1de0517db80b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>51fac4ea-f17b-4453-bd0a-956a826c9ab9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'make' and @name = 'make' and (text() = 'Select makeAcuraAudiBMWBuickCadillacChevroletChryslerDodgeFiatFordGMCHondaHummerHyundaiInfinitiJaguarJeepKiaLand RoverLexusLincolnMazdaMercedesMercuryMitsubishiNissan' or . = 'Select makeAcuraAudiBMWBuickCadillacChevroletChryslerDodgeFiatFordGMCHondaHummerHyundaiInfinitiJaguarJeepKiaLand RoverLexusLincolnMazdaMercedesMercuryMitsubishiNissan')]</value>
      <webElementGuid>15a757c3-d431-4780-b66d-e18c76d49542</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
