<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_ScheduledDoneCancelled (1)</name>
   <tag></tag>
   <elementGuidId>797c2ab7-f0cf-448d-a235-3e5307069881</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#newStatus</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='newStatus']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>d8640304-db2f-4f52-8492-e4a54e954145</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500</value>
      <webElementGuid>c8f44c09-7a8b-4293-b95e-1dca98a17b7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>newStatus</value>
      <webElementGuid>7f4a049b-a9d6-4d3c-be48-5b035802604a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ScheduledDoneCancelled</value>
      <webElementGuid>178ce2ff-8289-4b10-8ae7-24e6d28d67be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;newStatus&quot;)</value>
      <webElementGuid>6da77551-1695-4603-b471-7e856fc034c9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='newStatus']</value>
      <webElementGuid>619b28e2-d160-4504-a48d-c900e28c90bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//p[@id='modal-modal-description']/select</value>
      <webElementGuid>8cc9f150-bcaa-4282-938c-36c8f7c193f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Update Appointment'])[1]/preceding::select[1]</value>
      <webElementGuid>30b6646b-4f64-4556-be4d-fdc27781811c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close'])[1]/preceding::select[1]</value>
      <webElementGuid>58f0c2b1-4839-41ee-b294-1ec66e3a133d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>7a1f4cba-afdf-4676-a4f4-05f9ca031360</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'newStatus' and (text() = 'ScheduledDoneCancelled' or . = 'ScheduledDoneCancelled')]</value>
      <webElementGuid>d3fd5509-19df-4fad-a7a3-1c91c45c1177</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
