<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select Body TypeSedanCoupeHatchbackC_f844f0</name>
   <tag></tag>
   <elementGuidId>bbd35f5e-15f5-45af-bbcb-4b0bfb6837d9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#body</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='body']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>fa258ba2-ba0b-4cf3-8c4f-5af9c0da7713</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>body</value>
      <webElementGuid>e51f3283-03c5-4a3a-ab21-9be84061db81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>body</value>
      <webElementGuid>74f4cd02-c87e-4cb6-9d02-bb27f99039b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>215edc1a-3be0-47eb-b165-cdcd8d2df035</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select Body TypeSedanCoupeHatchbackConvertibleSUVVanPickup Truck</value>
      <webElementGuid>d770db1c-0503-4c12-aedc-1b41a22bc614</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;body&quot;)</value>
      <webElementGuid>40a843ba-0356-4d62-bc66-7d0535815b9d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='body']</value>
      <webElementGuid>b3a909ac-8932-48f4-9382-f6f2ff20be71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/main/div/div[2]/form/div[4]/select</value>
      <webElementGuid>58d48429-f5e4-4e1c-9841-e10119c64e27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Body:'])[1]/following::select[1]</value>
      <webElementGuid>72ccc281-c13b-4393-90df-c54edc27ccb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Model:'])[1]/following::select[2]</value>
      <webElementGuid>9c337910-dc99-48a5-891e-af4ef73cda50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Year:'])[1]/preceding::select[1]</value>
      <webElementGuid>77dad720-28c0-4020-86f5-ad3779267fc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Color:'])[1]/preceding::select[2]</value>
      <webElementGuid>1fe49bf6-202d-4384-bf23-a9c71fbfd157</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/select</value>
      <webElementGuid>6179bb6c-cde5-429e-ac7c-36945f4db305</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'body' and @name = 'body' and (text() = 'Select Body TypeSedanCoupeHatchbackConvertibleSUVVanPickup Truck' or . = 'Select Body TypeSedanCoupeHatchbackConvertibleSUVVanPickup Truck')]</value>
      <webElementGuid>50c3e7c3-f5c0-4f96-8737-baed70cd903c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
